### ISSUE TITLE
Приложение падает с ошибкой

### ISSUE THREAD

**Issue by surious-type** [GreyRuler/app-android#5]

**Comment by surious-type** [comment]
**Шаги для воспроизведения**
1. Запускаем проект
2. Кликаем на like или share
3. Приложение вылетает

**Ожидаемый результат:**
1. При клики на кнопку like, изменяется состояние кнопки и меняется кол-во лайков
2. При клики на кнопку share, увеличивается кол-во репостов

**В результате приложение падает с ошибкой**
Logcat: 
Process: ru.netology.nmedia, PID: 6966
    kotlin.UninitializedPropertyAccessException: lateinit property post has not been initialized
        at ru.netology.nmedia.repo.impl.PostsAdapter$ViewHolder.lambda-2$lambda-1(PostsAdapter.kt:43)
        at ru.netology.nmedia.repo.impl.PostsAdapter$ViewHolder.$r8$lambda$E448Cs4NBmH40FFh3ywEMtaZqmk(Unknown Source:0)
        at ru.netology.nmedia.repo.impl.PostsAdapter$ViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Окружение: **
1. ОС Windows 10 64
2. Версия Kotlin: 211-1.6.20-release-275-AS7442.40
3. Ссылка на исходники проекта на GitHub: https://github.com/GreyRuler/app-android/pull/6
